### ISSUE TITLE
Wrong abbreviations

### ISSUE THREAD

**Issue by LoganDark** [olivere/humanize#1]
`kB` should be `KiB`, since we're talking about 1,024 bytes and not 1,000
`MB` should be `MiB`, since we're talking about 1,048,576 bytes and not 1,000,000

**Comment by olivere** [comment]
You are right. This library was only meant to be used in a training course, as an example for how to access external packages via `go get` and import paths. Don't rely on this library! I may delete it any time now. The functionality is easy enough to replicate.
